env_file:
  - path: './.env'
    required: true # default
  - path: './dev.env'
    required: false

services:
  db_init:
    env_file:
      - './db_init/.env'
    build: './db_init/Dockerfile'
    volumes:
      - type: volume
        source: mariadb_cert
        target: ${SQL_CERTIF_PATH}
        read_only: true
      - type: volume
        source: client_ssl_cert
        taget: ${CLIENT_CERTIF_PATH}
    healthcheck:
      test: ["bash", "-c", "[-f ]"]
      interval: 1s
      timeout: 1s
      retries: 30
    
  mariadb:
    image : mariadb:3.2
    restart: always
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mariadb_data
        target: /var/lib/mysql
        security_opt:
          - label:disable
      - type: volume
        source: mariadb_conf
        taget: /etc/mysql/conf.d
        read_only: true
      - type: volume
        source: mariadb_cert
        target: ${SQL_CERTIF_PATH}
        read_only: true
    environment:
      MARIADB_ROOT_PASSWORD: example

volumes:
  mariadb_cert:
    driver: local
  mariadb_conf:
    driver: local
  mariadb_data:
    driver: local
  client_ssl_cert:
    driver: local

networks:
  sql-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16
          gateway: 10.5.0.1